### ISSUE TITLE
Use a deploy key instead of a personal access token

### ISSUE THREAD

**Issue by asmeurer** [crazy-max/ghaction-github-pages#1]
Personal access tokens provide full access to someone's account if they are leaked. It would be better to use a deploy key, which grants only push access to the specific repo.

**Comment by crazy-max** [comment]
Personal Access Token is used to to trigger a page build on a public repository. Everything is explained in the [Limitation](https://github.com/crazy-max/ghaction-github-pages#warning-limitation) section of the README.

GitHub team [currently working on it](https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869). We have to wait to remove this workaround until they fix it.

**Comment by harrybiddle** [comment]
One thing that would be useful would be to specify in the README which permissions the personal access token needs - presumably it is only "repo"?

**Comment by crazy-max** [comment]
@harrybiddle Yes good idea, I will update the README about this.

**Comment by crazy-max** [comment]
Personal Access Token is not required anymore to trigger a page build on a public repository. Nothing official from GitHub but everything seems to work for me on several repositories with the built-in `GITHUB_TOKEN` (public and private).
