### ISSUE TITLE
Could not pass environment variable to `with` step of workflow

### ISSUE THREAD

**Issue by NSKoohkan** [crazy-max/ghaction-github-pages#117]
### Behaviour
 
Could not find build dir in with step, example of failed job can find here:
https://github.com/DynamicKit/VersionKit/runs/825367023?check_suite_focus=true 

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: $BUILD_LOCATION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_LOCATION: public

**Comment by NSKoohkan** [comment]
Example of successful job with hardcoded build directory
https://github.com/DynamicKit/VersionKit/runs/825393851?check_suite_focus=true

**Comment by crazy-max** [comment]
@NSKoohkan 

> Could not pass environment variable to `with` step of workflow

You cannot ref an env var in an `input`. It's a core behavior and has nothing to do with this action. I suggest to open an issue on https://github.com/actions/runner instead.

**Comment by m6w6** [comment]
Sorry, for stumping in, but I am suffering from a similar issue, because I tried to use contexts in the commit message.

Any idea how to dynamically create the commit message?
