### ISSUE TITLE
fatal: empty ident name (for <ss@users.noreply.github.com>) not allowed

### ISSUE THREAD

**Issue by SummerSec** [crazy-max/ghaction-github-pages#180]
#### Steps to reproduce this issue

1.
https://github.com/SummerSec/SummerSec/actions/runs/3358344524/jobs/5565173197
https://github.com/SummerSec/SummerSec/actions/runs/3358344524/workflow
2.
3.

#### Expected behaviour

> Tell me what should happen

#### Actual behaviour

> Tell me what happens instead

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
# paste your YAML workflow file here and remove sensitive data
```

### Logs
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/47944478/198925809-fcb4a46e-1d4a-4f09-90fc-c5af2c7d18f3.png">

> Download the [log file of your build](https://docs.github.com/en/actions/managing-workflow-runs/using-workflow-run-logs#downloading-logs)
> and [attach it](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

**Comment by crazy-max** [comment]
looks to be a duplicated of #183
