### ISSUE TITLE
git exits with 128 in my action

### ISSUE THREAD

**Issue by asm0dey** [crazy-max/ghaction-github-pages#183]
#### Steps to reproduce this issue

1. In the repo https://github.com/asm0dey/kotlin-spring-webinar
2. On the "Deploy pages step"
3. I get the following log:

```
  ##[debug]Force push
  /usr/bin/git push --force ***github.com/asm0dey/kotlin-spring-webinar.git gh-pages
  remote: Permission to asm0dey/kotlin-spring-webinar.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/asm0dey/kotlin-spring-webinar.git/': The requested URL returned error: 403
  Error: The process '/usr/bin/git' failed with exit code 128
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Deploy pages
```

#### Expected behaviour

> should be published successfully

### Configuration

* Repository URL (if public):  https://github.com/asm0dey/kotlin-spring-webinar
* Build URL (if public): https://github.com/asm0dey/kotlin-spring-webinar/actions/runs/3990779289/jobs/6846465251

```yml
name: Deploy pages
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run:  npm i -g @slidev/cli
      - name: Build
        run: slidev build --base kotlin-spring-webinar
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: dist
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by MohnishKalia** [comment]
Was running into this issue as well and believe I have found a fix. The default GITHUB_TOKEN secret for the action doesn't appear to have the [permission](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) to write to the contents of the repository. Adding the following to the top of the action below `name:` fixed it for me.

```yml
permissions: 
  contents: write
```

**Comment by DarrenDanielDay** [comment]
Here's the doc:

<https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#setting-the-permissions-of-the-github_token-for-your-repository>
 
Adding permission in the config file works, and you can also modify the GitHub Actions settings of your repository to enable write permissions without modifying the config file.

![image](https://user-images.githubusercontent.com/43780355/214784684-63f32d7e-43ec-49ec-82ce-4085d23e4d14.png)

**Comment by asm0dey** [comment]
Thanks folks! Probably it should be added into the doc (or did I miss it?)
