### ISSUE TITLE
Allow pushing without using --force

### ISSUE THREAD

**Issue by asmeurer** [crazy-max/ghaction-github-pages#2]
Not using --force should be the default IMO.

**Comment by crazy-max** [comment]
@asmeurer As GitHub Pages branch reflects your generated website, it's not really under version control so `--force` is required to push to avoid conflicts. This method is currently used by Jekyll, Hugo and others static websites generators. So why does that bother you?

**Comment by asmeurer** [comment]
gh-pages is under version control. It's just another git branch.

**Comment by crazy-max** [comment]
I know that's why I said "not really"

**Comment by asmeurer** [comment]
It is really under version control. And there are advantages of using that fact. For instance, if you don't force push, you can easily revert a broken change directly, without waiting for a rebuild. Conversely, there are very few advantages to force pushing for most use cases.

**Comment by crazy-max** [comment]
Ok I see, I will take a look on this.

**Comment by ozkriff** [comment]
Just as a precedent: Travis's pages deployment has a [`keep_history` option](https://docs.travis-ci.com/user/deployment/pages):

> `keep_history`: Optional, create incremental commit instead of doing push force, defaults to `false`.

**Comment by crazy-max** [comment]
@asmeurer Fixed in [latest release](https://github.com/crazy-max/ghaction-github-pages/releases/tag/v1.2.0) through `keep_history` input.
@ozkriff Thanks for the hint ;)
