### ISSUE TITLE
Exit successfully on empty commit

### ISSUE THREAD

**Issue by Shatur95** [crazy-max/ghaction-github-pages#45]
**Is your feature request related to a problem? Please describe**
If I disable the option `allow_empty_commit`, then every time when I update my workflow file (or any other file not related to website), deploy is triggered and I get an error because there is no changes in website.

**Describe the solution you'd like**
It would be great to exit the action successfully with an empty commit, because if I activate the [continue-on-error](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) option, the action will complete successfully with any other error, which is not safe.

**Describe alternatives you've considered**
This behavior could be optional with the additional parameter or `allow_empty_commit` could be an enumeration with the third option like `skip`.

**Comment by crazy-max** [comment]
@Shatur95 Can you post a link to your repo where this behavior occurs?

**Comment by Shatur95** [comment]
I made a typo, I meant disabling `allow_empty_commit`.
[Here](https://github.com/crow-translate/hugo-website) is the example. I do not want to have an empty commits, but if I enable this option I will have an error on every commit that do not change my website.

**Comment by crazy-max** [comment]
@Shatur95 Ok this is the expected behavior like it's done [on Travis](https://docs.travis-ci.com/user/deployment/pages/) and others CI environments. So in your case you should trigger a build only for files related to your website with [`on.<push|pull_request>.paths`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths) for example.

**Comment by Shatur95** [comment]
But in this case I need to exclude `.yml` file too. If I make a configuration error in `.yml` when sending the site, and then fix it in the next commit, the site will not be deployed.

**Comment by crazy-max** [comment]
I have made some changes. Can you try it with the following `uses` in your step: `uses: crazy-max/ghaction-github-pages@check-status`?

**Comment by Shatur95** [comment]
Tested, it works.

**Comment by Shatur95** [comment]
Thank you!
Could you draft a new release?

**Comment by crazy-max** [comment]
@Shatur95 Should be good ;)

**Comment by Shatur95** [comment]
Thanks :)
