### ISSUE TITLE
should not use GITHUB_ prefix

### ISSUE THREAD

**Issue by sinkcup** [crazy-max/ghaction-github-pages#53]
GITHUB_PAT should not use GITHUB_ prefix, it's reserved.

https://help.github.com/en/actions/automating-your-workflow-with-github-actions/using-environment-variables

> Note: GitHub reserves the GITHUB_ environment variable prefix for internal use by GitHub. Setting an environment variable or secret with the GITHUB_ prefix will result in an error.

**Comment by crazy-max** [comment]
`GITHUB_PAT` is not required anymore. See #1.
