### ISSUE TITLE
[suggestion] commit only into a directory of the target repo, leaving the rest unmodified

### ISSUE THREAD

**Issue by sarahBuisson** [crazy-max/ghaction-github-pages#76]
It could be a good idea to add a target path field, who, when used,
 - create the directory of the path (if not existing)
 - add the content of the build_dir into the targetPathField directory
 - and leave the rest of the repo unmodified.

**Comment by crazy-max** [comment]
@sarahBuisson What's the point? Do you have a concrete use case?

**Comment by sarahBuisson** [comment]
I use gh-pages to publish the evolution of quality metrics of my project : I need the previous metrics along the new-ones.

**Comment by crazy-max** [comment]
You can already do this using the `keep_history` input.

**Comment by sarahBuisson** [comment]
no, if you want to display it, you need it side by side. the published website of github page don't use the history

**Comment by crazy-max** [comment]
> the published website of github page don't use the history

@sarahBuisson Not if you use the `keep_history` input as I said. This way the git history of the `target_branch` will be kept.

To summarize if your current git branch deployed on GitHub Pages contains:

```
myfolder20200415\mypage.html
index.html
```

And you want to deploy a new file named `myfolder20200416\mypage.html`, the result on the `target_branch` will be:

```
myfolder20200415\mypage.html
myfolder20200416\mypage.html
index.html
```

**Comment by sarahBuisson** [comment]
I will try it. Thanks!
